export const AdvancedsItems = [
  {
    saleTop: "39",
    img: "https://github.com/nhannn87dn/Learn-ReactJs-Basic/blob/main/3.Homeworks/Session-04-Rendering/Exercise-5-Advanceds/1.jpg?raw=true",
    cost: "1,422.7",
    sale: "1,025.5",
    salePercent: "18",
    label: "LG White Front Load Stream Washer",
    sold: "10",
  },
  {
    saleTop: "13",
    img: "https://github.com/nhannn87dn/Learn-ReactJs-Basic/blob/main/3.Homeworks/Session-04-Rendering/Exercise-5-Advanceds/2.jpg?raw=true",
    cost: "96",
    sale: "85",
    salePercent: "18",
    label: "Edifier Powered Bookshelf Speakers",
    sold: "15",
  },
  {
    saleTop: "37",
    img: "https://github.com/nhannn87dn/Learn-ReactJs-Basic/blob/main/3.Homeworks/Session-04-Rendering/Exercise-5-Advanceds/3.jpg?raw=true",
    cost: "62.99",
    sale: "45.9",
    salePercent: "18",
    label: "Amcrest Security Camera in White Color",
    sold: "20",
  },
  {
    saleTop: "27",
    img: "https://github.com/nhannn87dn/Learn-ReactJs-Basic/blob/main/3.Homeworks/Session-04-Rendering/Exercise-5-Advanceds/4.jpg?raw=true",
    cost: "41.99",
    sale: "32.99",
    salePercent: "18",
    label: "Grand Slam Indoor Of Show Jumping Novel",
    sold: "22",
  },
  {
    saleTop: "6",
    img: "https://github.com/nhannn87dn/Learn-ReactJs-Basic/blob/main/3.Homeworks/Session-04-Rendering/Exercise-5-Advanceds/5.jpg?raw=true",
    cost: "106.96",
    sale: "100.99",
    salePercent: "18",
    label: "Sound Intone I65 Earphone White Version",
    sold: "10",
  },
  {
    saleTop: "18",
    img: "https://github.com/nhannn87dn/Learn-ReactJs-Basic/blob/main/3.Homeworks/Session-04-Rendering/Exercise-5-Advanceds/6.jpg?raw=true",
    cost: "670.2",
    sale: "567.8",
    salePercent: "18",
    label: "Korea Long Sofa Frabic In Blue Navy Color",
    sold: "79",
  },
];
